apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyAJImF1dGhzIjoge30sIAkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwgCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwgCSJwbHVnaW5zIjogeyAJCSJkZWJ1ZyI6IHsgCQkJImhvb2tzIjogImV4ZWMiIAkJfSwgCQkic2NvdXQiOiB7IAkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIgCQl9IAl9LCAJImZlYXR1cmVzIjogeyAJCSJob29rcyI6ICJ0cnVlIiAJfSwgCSJhdXRocyI6IHsgCQkiZ2hjci5pbyI6IHsgCQkJImF1dGgiOiAiYTI1aGRYUnBiSFZ6T21kb2NGOVlNRmRQYWpaUmN6Qk1jVUpSYldGNGJrbFJOa1ExUldKWGVXZEVRV0V6TW5CSlVXRT0iIAkJfSAJfSB9
type: kubernetes.io/dockerconfigjson
